"""Generate and run the centralized ROS 2 RMW benchmark matrix.

The generator writes explicit, reviewable YAML.  Runs remain serial because
timing benchmarks must not contend with one another::

    python -m netcom_zen.harness.centralized_lab generate
    sudo .pixi/envs/ros2/bin/python -m netcom_zen.harness.sweep \
      scenarios/centralized/single_n32_sweep.yaml -o results/centralized/single_n32
"""
from __future__ import annotations

import argparse
import asyncio
import copy
import csv
import hashlib
import json
import os
import platform
import shutil
import statistics
import subprocess
import time
from pathlib import Path

import yaml

from ..config import Scenario
from .dds_scenarios import _MINIMAL_RADIO
from . import report
from .sweep import apply_override, cell_name, expand, run_sweep

RMWS = ["fastrtps", "cyclonedds", "zenoh"]
CAPACITY_CLIENTS = [4, 16, 32, 64, 96, 128]
HA_CLIENTS = [32, 96]
INITIAL_MEMORY_GIB = 12
CONTINUATION_MEMORY_GIB = 8
LAN_HOSTS = {
    "local": {
        "addr": "192.168.1.6", "iface": "wlp130s0f0", "max_nodes": 128},
    "mini": {
        "ssh": "orm_small_nix@192.168.1.9",
        "addr": "192.168.1.9", "iface": "wlp2s0", "max_nodes": 24},
}
REPO_ROOT = Path(__file__).resolve().parents[3]


def centralized_scenario(
    n_clients: int,
    *,
    mode: str = "single",
    rmw: str = "zenoh",
    duration_s: float = 60.0,
    failure_at_s: float | None = None,
) -> dict:
    n_servers = 1 if mode == "single" else 2
    server_ids = [f"s{i + 1}" for i in range(n_servers)]
    if mode in {"active_active", "active_passive"}:
        failure_at_s = 45.0 if failure_at_s is None else failure_at_s
        duration_s = max(duration_s, 90.0)
    nodes = [
        {"id": sid, "waypoints": [[0.0, 0.0]], "speed_mps": 0.01}
        for sid in server_ids
    ] + [
        {"id": f"c{i + 1}", "waypoints": [[0.0, 0.0]], "speed_mps": 0.01}
        for i in range(n_clients)
    ]
    central = {
        "server_ids": server_ids,
        "profile_label": "tuned",
        "mode": mode,
        "primary_server_id": server_ids[0],
        "failure_at_s": failure_at_s,
        "discovery_mode": "centralized",
        "telemetry_period_ms": 200,
        "telemetry_payload_bytes": 255,
        "telemetry_reliability": "best_effort",
        "command_period_ms": 1000,
        "command_payload_bytes": 255,
        "rpc_period_ms": 1000,
        "rpc_timeout_ms": 2000,
    }
    if mode == "active_passive":
        central["standby_activate_after_s"] = failure_at_s
    data = {
        "name": f"central-{mode}-n{n_clients}-{rmw}",
        "duration_s": duration_s,
        "seed": 0,
        "substrate": "bridge",
        "radio": _MINIMAL_RADIO,
        "nodes": nodes,
        "workload": "ros2",
        "ros2": {
            "rmw": rmw,
            "topology": "centralized",
            "centralized": central,
        },
    }
    Scenario.model_validate(data)
    return data


def centralized_lan_scenario(
        n_clients: int, *, mode: str = "single",
        rmw: str = "zenoh", inverted: bool = False) -> dict:
    data = centralized_scenario(
        n_clients, mode=mode, rmw=rmw,
        duration_s=90.0 if mode in {"active_active", "active_passive"} else 60.0)
    data["substrate"] = "lan"
    data["hosts"] = LAN_HOSTS
    servers = data["ros2"]["centralized"]["server_ids"]
    # Normal placement: primary on the small remote box, redundant server on
    # the rig.  Inverted single-server check moves the server to the rig and
    # puts at most 24 clients on the mini.
    for node in data["nodes"]:
        if node["id"] == servers[0]:
            node["host"] = "local" if inverted else "mini"
        elif len(servers) > 1 and node["id"] == servers[1]:
            node["host"] = "mini" if inverted else "local"
        elif inverted:
            idx = int(node["id"].removeprefix("c"))
            node["host"] = "mini" if idx <= min(24, n_clients) else "local"
        else:
            node["host"] = "local"
    Scenario.model_validate(data)
    return data


def _write_yaml(path: Path, value: dict) -> None:
    path.write_text(
        "# AUTO-GENERATED by netcom_zen.harness.centralized_lab\n"
        + yaml.dump(value, default_flow_style=False, sort_keys=False))


def _stock_profile(rmw: str) -> dict:
    return {
        "ros2.rmw": rmw,
        "ros2.centralized.profile_label": "stock",
        "ros2.centralized.discovery_mode": (
            "centralized" if rmw == "zenoh" else "native"),
        "ros2.centralized.telemetry_reliability": "reliable",
        "ros2.socket_buffer_bytes": 0,
    }


def _fallback_tuned_profile(rmw: str) -> dict:
    return {
        "ros2.rmw": rmw,
        "ros2.centralized.profile_label": "tuned",
        "ros2.centralized.discovery_mode": "centralized",
        "ros2.centralized.telemetry_reliability": "best_effort",
        "ros2.socket_buffer_bytes": 0,
    }


def _profile_cells(locked_profiles: dict | None) -> list[dict]:
    profiles = (locked_profiles or {}).get("selected", {})
    cells = []
    for rmw in RMWS:
        cells.append(_stock_profile(rmw))
        chosen = dict(profiles.get(rmw, _fallback_tuned_profile(rmw)))
        chosen["ros2.rmw"] = rmw
        chosen["ros2.centralized.profile_label"] = "tuned"
        cells.append(chosen)
    return cells


def generate(out_dir: Path, locked_profiles: dict | None = None) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for n in CAPACITY_CLIENTS:
        base = out_dir / f"single_n{n}.yaml"
        sweep = out_dir / f"single_n{n}_sweep.yaml"
        _write_yaml(base, centralized_scenario(n))
        _write_yaml(sweep, {
            "base": base.name,
            "cells": _profile_cells(locked_profiles),
            "seeds": [0, 1, 2],
        })
        written.extend([base, sweep])

    # Rate and payload frontiers at N=64.  zip_axes keeps telemetry and RPC
    # rates paired rather than creating meaningless cross-products.
    rate = out_dir / "rate_n64_sweep.yaml"
    _write_yaml(rate, {
        "base": "single_n64.yaml",
        "cells": [
            c for c in _profile_cells(locked_profiles)
            if c["ros2.centralized.profile_label"] == "tuned"],
        "zip_axes": {
            "ros2.centralized.telemetry_period_ms": [200, 50, 20],
            "ros2.centralized.rpc_period_ms": [1000, 200, 100],
        },
        "seeds": [0, 1, 2],
    })
    payload = out_dir / "payload_n64_sweep.yaml"
    _write_yaml(payload, {
        "base": "single_n64.yaml",
        "cells": [
            c for c in _profile_cells(locked_profiles)
            if c["ros2.centralized.profile_label"] == "tuned"],
        "zip_axes": {
            "ros2.centralized.telemetry_payload_bytes": [255, 4096, 65536],
            "ros2.centralized.command_payload_bytes": [255, 4096, 65536],
        },
        "seeds": [0, 1, 2],
    })
    written.extend([rate, payload])

    # Bounded calibration cells.  These remain separate from the main curves:
    # select a Pareto profile from N=32/96, then record that choice in the
    # generated tuned bases rather than silently optimizing on test cells.
    for n in (32, 96):
        for rmw in RMWS:
            base = out_dir / f"tune_{rmw}_n{n}.yaml"
            sweep = out_dir / f"tune_{rmw}_n{n}_sweep.yaml"
            _write_yaml(base, centralized_scenario(n, rmw=rmw))
            axes = {
                "ros2.centralized.telemetry_reliability":
                    ["reliable", "best_effort"],
            }
            # Zenoh's centralized workload always has a router.  A "native"
            # value is therefore a duplicate no-op, not a calibration cell.
            if rmw != "zenoh":
                axes["ros2.centralized.discovery_mode"] = [
                    "native", "centralized"]
            if rmw in {"fastrtps", "cyclonedds"}:
                axes["ros2.socket_buffer_bytes"] = [
                    0, 16 * 1024 * 1024, 64 * 1024 * 1024]
            _write_yaml(sweep, {
                "base": base.name, "axes": axes,
                "cells": [{
                    "ros2.centralized.profile_label": "candidate"}],
                "seeds": [0, 1, 2]})
            written.extend([base, sweep])

    for mode in ("active_active", "active_passive", "sharded"):
        for n in HA_CLIENTS:
            base = out_dir / f"{mode}_n{n}.yaml"
            sweep = out_dir / f"{mode}_n{n}_sweep.yaml"
            _write_yaml(base, centralized_scenario(n, mode=mode))
            _write_yaml(sweep, {
                "base": base.name,
                "cells": [
                    c for c in _profile_cells(locked_profiles)
                    if c["ros2.centralized.profile_label"] == "tuned"],
                "seeds": [0, 1, 2, 3, 4] if mode != "sharded" else [0, 1, 2],
            })
            written.extend([base, sweep])

    lan_dir = out_dir / "lan"
    lan_dir.mkdir(exist_ok=True)
    for n in (16, 64, 96):
        base = lan_dir / f"single_n{n}.yaml"
        sweep = lan_dir / f"single_n{n}_sweep.yaml"
        _write_yaml(base, centralized_lan_scenario(n))
        _write_yaml(sweep, {
            "base": base.name,
            "cells": _profile_cells(locked_profiles),
            "seeds": [0, 1, 2],
        })
        written.extend([base, sweep])
    inverted = lan_dir / "single_n64_inverted.yaml"
    inverted_sweep = lan_dir / "single_n64_inverted_sweep.yaml"
    _write_yaml(inverted, centralized_lan_scenario(64, inverted=True))
    _write_yaml(inverted_sweep, {
        "base": inverted.name,
        "cells": _profile_cells(locked_profiles),
        "seeds": [0, 1, 2],
    })
    written.extend([inverted, inverted_sweep])
    for mode in ("active_active", "active_passive", "sharded"):
        for n in HA_CLIENTS:
            base = lan_dir / f"{mode}_n{n}.yaml"
            sweep = lan_dir / f"{mode}_n{n}_sweep.yaml"
            _write_yaml(base, centralized_lan_scenario(n, mode=mode))
            _write_yaml(sweep, {
                "base": base.name,
                "cells": [
                    c for c in _profile_cells(locked_profiles)
                    if c["ros2.centralized.profile_label"] == "tuned"],
                "seeds": (
                    [0, 1, 2, 3, 4]
                    if mode != "sharded" else [0, 1, 2]),
            })
            written.extend([base, sweep])
    high = lan_dir / "rate_n64_sweep.yaml"
    _write_yaml(high, {
        "base": "single_n64.yaml",
        "cells": [
            c for c in _profile_cells(locked_profiles)
            if c["ros2.centralized.profile_label"] == "tuned"],
        "zip_axes": {
            "ros2.centralized.telemetry_period_ms": [200, 50, 20],
            "ros2.centralized.rpc_period_ms": [1000, 200, 100],
        },
        "seeds": [0, 1, 2],
    })
    written.append(high)
    return written


def _available_bytes() -> int:
    import psutil
    return psutil.virtual_memory().available


def _disk_free(path: Path) -> int:
    return shutil.disk_usage(path).free


def preflight(
        root: Path, *, require_root: bool = True,
        resumed: bool = False) -> None:
    disk_floor = (3 if resumed else 10) * 1024**3
    if _disk_free(root) < disk_floor:
        state = "resume" if resumed else "startup"
        raise RuntimeError(
            f"evaluation needs at least {disk_floor / 1024**3:.0f} GiB "
            f"free at {state}")
    memory_floor = (
        CONTINUATION_MEMORY_GIB if resumed else INITIAL_MEMORY_GIB)
    if _available_bytes() < memory_floor * 1024**3:
        raise RuntimeError(
            f"evaluation needs at least {memory_floor} GiB available memory "
            f"at {'resume' if resumed else 'startup'}")
    if require_root and os.geteuid() != 0:
        raise PermissionError(
            "bridge evaluation needs root; rerun with the ros2 Python under sudo")


def _middleware_packages() -> list[dict]:
    """Read exact ROS/RMW versions from the Pixi environment metadata."""
    prefix = REPO_ROOT / ".pixi/envs/ros2"
    tokens = (
        "rmw", "fastrtps", "cyclonedds", "zenoh", "fastcdr",
        "libzenohc")
    packages = []
    for path in sorted((prefix / "conda-meta").glob("*.json")):
        try:
            item = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        name = str(item.get("name", "")).lower()
        if any(token in name for token in tokens):
            packages.append({
                key: item.get(key)
                for key in ("name", "version", "build", "channel")
            })
    return packages


def write_provenance(out_root: Path) -> Path:
    out_root.mkdir(parents=True, exist_ok=True)

    def command(*args: str) -> str:
        try:
            p = subprocess.run(
                args, text=True, capture_output=True, cwd=REPO_ROOT)
            return (p.stdout + p.stderr).strip()
        except OSError as exc:
            return f"{type(exc).__name__}: {exc}"

    lock = (REPO_ROOT / "pixi.lock").read_bytes()
    vmstat = {}
    for line in Path("/proc/vmstat").read_text().splitlines():
        key, value = line.split()
        if key in {"pswpin", "pswpout"}:
            vmstat[key] = int(value)
    data = {
        "recorded_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "git_commit": command("git", "rev-parse", "HEAD"),
        "git_status": command("git", "status", "--short"),
        "pixi_lock_sha256": hashlib.sha256(lock).hexdigest(),
        "kernel": platform.uname()._asdict(),
        "cpu": command("lscpu"),
        "memory": command("free", "-b"),
        "disk": command("df", "-B1", "."),
        "network_interfaces": command("ip", "-details", "-brief", "address"),
        "swap_counters": vmstat,
        "middleware_packages": _middleware_packages(),
    }
    path = out_root / "provenance.json"
    path.write_text(json.dumps(data, indent=2))
    return path


def finalize_provenance(out_root: Path) -> None:
    """Repair/version the preserved run-start provenance at report time."""
    path = out_root / "provenance.json"
    if not path.exists():
        return
    data = json.loads(path.read_text())
    vmstat = {}
    for line in Path("/proc/vmstat").read_text().splitlines():
        key, value = line.split()
        if key in {"pswpin", "pswpout"}:
            vmstat[key] = int(value)
    data["middleware_packages"] = _middleware_packages()
    data["report_generated_at"] = time.strftime(
        "%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    data["swap_counters_at_report"] = vmstat
    path.write_text(json.dumps(data, indent=2))


def _profile_key(row: dict) -> tuple:
    return (
        row.get("ros2.centralized.discovery_mode", row.get("discovery_mode")),
        row.get(
            "ros2.centralized.telemetry_reliability",
            row.get("telemetry_reliability")),
        row.get("ros2.socket_buffer_bytes", row.get(
            "socket_buffer_bytes", 0)),
    )


def lock_profiles(out_root: Path, scenario_root: Path) -> dict:
    selected: dict[str, dict] = {}
    pareto: list[dict] = []
    for rmw in RMWS:
        rows = []
        for n in (32, 96):
            d = out_root / "tune" / f"tune_{rmw}_n{n}"
            for row in report.aggregate(d):
                row["calibration_n"] = n
                rows.append(row)
        candidates = []
        for key in sorted({_profile_key(r) for r in rows}, key=str):
            group = [r for r in rows if _profile_key(r) == key]
            complete = (
                len(group) == 6 and all(r.get("complete") for r in group))
            centralized = key[0] == "centralized"
            def total(metric: str) -> float:
                return sum(float(r.get(metric) or 0) for r in group)
            p99s = [float(r["rpc_rtt_p99_ms"]) for r in group
                    if r.get("rpc_rtt_p99_ms") is not None]
            cpus = [
                float(r.get("server_cpu_peak_pct") or 0)
                + float(r.get("infrastructure_cpu_peak_pct") or 0)
                for r in group]
            item = {
                "rmw": rmw, "discovery_mode": key[0],
                "telemetry_reliability": key[1],
                "socket_buffer_bytes": key[2],
                "complete": complete, "centralized": centralized,
                "tight_passes": total("slo_tight_control"),
                "relaxed_passes": total("slo_relaxed"),
                "delivered_telemetry": total("telemetry_received"),
                "rpc_throughput": total("rpc_success_per_s"),
                "worst_rpc_p99_ms": max(p99s, default=float("inf")),
                "server_infrastructure_cpu": max(cpus, default=float("inf")),
            }
            candidates.append(item)
        eligible = [c for c in candidates
                    if c["complete"] and c["centralized"]]
        if not eligible:
            raise RuntimeError(
                f"no complete centralized calibration profile for {rmw}")
        chosen = min(eligible, key=lambda c: (
            -c["tight_passes"], -c["relaxed_passes"],
            -c["delivered_telemetry"], -c["rpc_throughput"],
            c["worst_rpc_p99_ms"], c["server_infrastructure_cpu"],
            c["discovery_mode"], c["telemetry_reliability"],
            c["socket_buffer_bytes"],
        ))
        for c in candidates:
            c["selected"] = c is chosen
        pareto.extend(candidates)
        selected[rmw] = {
            "ros2.centralized.discovery_mode": chosen["discovery_mode"],
            "ros2.centralized.telemetry_reliability":
                chosen["telemetry_reliability"],
            "ros2.socket_buffer_bytes": chosen["socket_buffer_bytes"],
        }
    locked = {
        "selection_policy": [
            "complete centralized candidates only", "tight SLO passes",
            "relaxed SLO passes", "delivered telemetry", "RPC throughput",
            "worst RPC p99", "server plus infrastructure CPU"],
        "selected": selected, "pareto": pareto,
    }
    path = out_root / "locked_profiles.json"
    path.write_text(json.dumps(locked, indent=2))
    generate(scenario_root, locked)
    return locked


PHASE_SWEEPS = {
    "tune": [
        f"tune_{rmw}_n{n}_sweep.yaml"
        for rmw in RMWS for n in (32, 96)],
    "bridge-core": [
        *[f"single_n{n}_sweep.yaml" for n in CAPACITY_CLIENTS],
        "rate_n64_sweep.yaml", "payload_n64_sweep.yaml"],
    "bridge-ha": [
        f"{mode}_n{n}_sweep.yaml"
        for mode in ("active_active", "active_passive", "sharded")
        for n in HA_CLIENTS],
    "lan": [
        *[f"lan/single_n{n}_sweep.yaml" for n in (16, 64, 96)],
        "lan/single_n64_inverted_sweep.yaml",
        *[f"lan/{mode}_n{n}_sweep.yaml"
          for mode in ("active_active", "active_passive", "sharded")
          for n in HA_CLIENTS],
        "lan/rate_n64_sweep.yaml"],
}


def _result_name(relative: str) -> str:
    return relative.removesuffix("_sweep.yaml").replace("lan/", "")


def _planned_metadata(
        sweep_path: Path, sweep: dict, overrides: dict) -> dict:
    """Canonical fields for a cell, even when its artifacts are malformed."""
    fallback = {
        "rmw": overrides.get("ros2.rmw"),
        "profile_label": overrides.get(
            "ros2.centralized.profile_label"),
        "server_mode": None,
        "n_clients": None,
        "n_servers": None,
    }
    try:
        cfg = yaml.safe_load(
            (sweep_path.parent / sweep["base"]).read_text())
        for key, value in overrides.items():
            apply_override(cfg, key, value)
        scenario = Scenario.model_validate(cfg)
        central = scenario.ros2.centralized
        if central is None:
            return fallback
        servers = set(central.server_ids)
        return {
            "rmw": scenario.ros2.rmw,
            "profile_label": central.profile_label,
            "server_mode": central.mode,
            "n_clients": sum(
                node.id not in servers for node in scenario.nodes),
            "n_servers": len(servers),
        }
    except Exception:
        return fallback


async def run_phase(
        phase: str, scenario_root: Path, out_root: Path) -> None:
    phase_root = out_root / phase
    phase_root.mkdir(parents=True, exist_ok=True)
    for relative in PHASE_SWEEPS[phase]:
        if _disk_free(out_root) < 3 * 1024**3:
            raise RuntimeError("phase stopped: disk free fell below 3 GiB")
        if _available_bytes() < CONTINUATION_MEMORY_GIB * 1024**3:
            raise RuntimeError(
                "cell not started: available memory is below "
                f"{CONTINUATION_MEMORY_GIB} GiB")
        sweep_path = scenario_root / relative
        result_dir = phase_root / _result_name(relative)
        for attempt in range(2):
            try:
                await run_sweep(sweep_path, result_dir)
                break
            except (OSError, RuntimeError, subprocess.SubprocessError):
                if attempt:
                    raise
                # Only infrastructure/spawn exceptions reach here. Completed
                # low-performance cells return normally and are never retried.
                await asyncio.sleep(2)


def combined_report(
        out_root: Path, scenario_root: Path | None = None) -> dict:
    scenario_root = scenario_root or REPO_ROOT / "scenarios/centralized"
    out_root.mkdir(parents=True, exist_ok=True)
    finalize_provenance(out_root)
    rows = []
    for phase, relatives in PHASE_SWEEPS.items():
        for relative in relatives:
            sweep_path = scenario_root / relative
            result_dir = out_root / phase / _result_name(relative)
            sweep_name = result_dir.name
            try:
                sweep = yaml.safe_load(sweep_path.read_text())
                expected = expand(sweep)
            except Exception as exc:
                rows.append({
                    "phase": phase,
                    "sweep": sweep_name,
                    "cell_name": None,
                    "cell_status": "malformed_plan",
                    "complete": False,
                    "failure_reason": (
                        f"cannot expand planned sweep {relative}: "
                        f"{type(exc).__name__}: {exc}"),
                })
                continue
            expected_metadata = {
                cell_name(overrides, seed):
                    _planned_metadata(sweep_path, sweep, overrides)
                for overrides, seed in expected}
            manifest = result_dir / "sweep_manifest.json"
            if not manifest.exists():
                for overrides, seed in expected:
                    name = cell_name(overrides, seed)
                    rows.append({
                        "phase": phase,
                        "sweep": sweep_name,
                        **expected_metadata[name],
                        **overrides,
                        "seed": seed,
                        "cell_name": name,
                        "cell_status": "missing",
                        "complete": False,
                        "failure_reason": (
                            f"missing sweep manifest: "
                            f"{manifest.relative_to(out_root)}"),
                    })
                continue
            try:
                aggregated = report.aggregate(result_dir)
            except Exception as exc:
                aggregated = [{
                    **overrides,
                    "seed": seed,
                    "cell_name": cell_name(overrides, seed),
                    "cell_status": "malformed",
                    "complete": False,
                    "failure_reason": (
                        f"malformed sweep results: "
                        f"{type(exc).__name__}: {exc}"),
                } for overrides, seed in expected]
            for row in aggregated:
                metadata = expected_metadata.get(
                    row.get("cell_name"), {})
                rows.append({
                    "phase": phase,
                    "sweep": sweep_name,
                    **metadata,
                    **row,
                })
    summary = {
        "planned": len(rows),
        "complete": sum(bool(r.get("complete")) for r in rows),
        "failed": sum(not r.get("complete") for r in rows),
        "rows": rows,
    }
    (out_root / "summary_all.json").write_text(
        json.dumps(summary, indent=2))
    keys = sorted({k for row in rows for k in row
                   if not isinstance(row.get(k), (dict, list))})
    with (out_root / "summary_all.csv").open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    summary["artifacts"] = write_analysis_artifacts(rows, out_root)
    (out_root / "summary_all.json").write_text(
        json.dumps(summary, indent=2))
    return summary


def _write_rows(out_root: Path, stem: str, rows: list[dict]) -> list[str]:
    json_path = out_root / f"{stem}.json"
    csv_path = out_root / f"{stem}.csv"
    json_path.write_text(json.dumps(rows, indent=2))
    keys = sorted({key for row in rows for key in row})
    with csv_path.open("w", newline="") as stream:
        writer = csv.DictWriter(
            stream, fieldnames=keys, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    return [json_path.name, csv_path.name]


def _replicate_tables(rows: list[dict]) -> tuple[list[dict], list[dict]]:
    """Return explicit SLO-capacity and replicate-variance summaries."""
    group_keys = (
        "phase", "sweep", "rmw", "profile_label", "server_mode",
        "n_clients", "n_servers",
        "ros2.centralized.telemetry_period_ms",
        "ros2.centralized.rpc_period_ms",
    )
    grouped: dict[tuple, list[dict]] = {}
    for row in rows:
        key = tuple(row.get(name) for name in group_keys)
        grouped.setdefault(key, []).append(row)

    slo_rows = []
    variance_rows = []
    variance_metrics = (
        "telemetry_delivery_ratio", "telemetry_received_per_s",
        "rpc_success_ratio", "rpc_success_per_s", "rpc_rtt_p99_ms",
        "ready_time_s", "command_gap_p99_ms", "command_duplicate_ratio",
        "command_failover_gap_s", "rpc_failover_gap_s",
        "server_cpu_peak_pct", "server_rss_peak_mb",
        "infrastructure_cpu_peak_pct", "infrastructure_rss_peak_mb",
    )
    for key, group in sorted(grouped.items(), key=lambda item: str(item[0])):
        base = dict(zip(group_keys, key))
        planned = len(group)
        complete_group = [row for row in group if row.get("complete")]
        complete_count = len(complete_group)
        relaxed_passes = sum(
            bool(r.get("slo_relaxed")) for r in complete_group)
        tight_passes = sum(
            bool(r.get("slo_tight_control")) for r in complete_group)
        slo_rows.append({
            **base,
            "replicates_planned": planned,
            "replicates_complete": complete_count,
            "all_complete": complete_count == planned,
            "relaxed_passes": relaxed_passes,
            "relaxed_pass_fraction": relaxed_passes / planned,
            "tight_passes": tight_passes,
            "tight_pass_fraction": tight_passes / planned,
        })
        for metric in variance_metrics:
            values = [
                float(row[metric]) for row in complete_group
                if row.get(metric) is not None]
            if not values:
                continue
            mean = statistics.mean(values)
            stdev = statistics.stdev(values) if len(values) > 1 else 0.0
            variance_rows.append({
                **base,
                "metric": metric,
                "replicates_with_value": len(values),
                "mean": mean,
                "stdev": stdev,
                "cv": abs(stdev / mean) if mean else None,
                "minimum": min(values),
                "maximum": max(values),
            })
    return slo_rows, variance_rows


def _sustainable_frontiers(slo_rows: list[dict]) -> list[dict]:
    """Maximum all-replicate capacity and paired offered-rate frontiers."""
    output = []
    for phase in ("bridge-core", "lan"):
        phase_rows = [row for row in slo_rows if row["phase"] == phase]
        for rmw in RMWS:
            rmw_rows = [row for row in phase_rows if row["rmw"] == rmw]
            for slo, fraction_key in (
                    ("relaxed", "relaxed_pass_fraction"),
                    ("tight_control", "tight_pass_fraction")):
                capacity = [
                    row for row in rmw_rows
                    if str(row["sweep"]).startswith("single_n")
                    and "inverted" not in str(row["sweep"])
                    and row["profile_label"] == "tuned"
                    and row["all_complete"]
                    and row[fraction_key] == 1.0]
                rates = [
                    row for row in rmw_rows
                    if row["sweep"] == "rate_n64"
                    and row["profile_label"] == "tuned"
                    and row["all_complete"]
                    and row[fraction_key] == 1.0]
                max_rate = max(
                    rates,
                    key=lambda row: (
                        1000 / row[
                            "ros2.centralized.telemetry_period_ms"],
                        1000 / row["ros2.centralized.rpc_period_ms"]),
                    default=None)
                output.append({
                    "phase": phase,
                    "rmw": rmw,
                    "slo": slo,
                    "maximum_sustainable_n": max(
                        (row["n_clients"] for row in capacity),
                        default=None),
                    "maximum_sustainable_telemetry_offered_per_s": (
                        max_rate["n_clients"] * 1000
                        / max_rate[
                            "ros2.centralized.telemetry_period_ms"]
                        if max_rate else None),
                    "maximum_sustainable_rpc_offered_per_s": (
                        max_rate["n_clients"] * 1000
                        / max_rate["ros2.centralized.rpc_period_ms"]
                        if max_rate else None),
                    "rate_telemetry_period_ms": (
                        max_rate[
                            "ros2.centralized.telemetry_period_ms"]
                        if max_rate else None),
                    "rate_rpc_period_ms": (
                        max_rate["ros2.centralized.rpc_period_ms"]
                        if max_rate else None),
                })
    return output


def _plot_metric(
        rows: list[dict], out_root: Path, filename: str,
        metrics: list[tuple[str, str]], *,
        selection=None, x_key: str = "n_clients") -> str:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    chosen = [
        row for row in rows
        if row.get("complete", True)
        and (selection is None or selection(row))]
    fig, axes = plt.subplots(
        len(metrics), 1, figsize=(9, max(4.5, 3.6 * len(metrics))),
        squeeze=False)
    for ax, (metric, label) in zip(axes[:, 0], metrics):
        series: dict[tuple, dict[float, list[float]]] = {}
        for row in chosen:
            x = row.get(x_key)
            value = row.get(metric)
            if x is None or value is None:
                continue
            key = (
                row.get("phase"), row.get("rmw"),
                row.get("profile_label"), row.get("server_mode"))
            series.setdefault(key, {}).setdefault(float(x), []).append(
                float(value))
        for key, points in sorted(series.items(), key=lambda item: str(item[0])):
            xs = sorted(points)
            ys = [statistics.mean(points[x]) for x in xs]
            errors = [
                statistics.stdev(points[x]) if len(points[x]) > 1 else 0
                for x in xs]
            ax.errorbar(
                xs, ys, yerr=errors, marker="o", capsize=2,
                label="/".join(str(part) for part in key if part is not None))
        ax.set_xlabel(x_key)
        ax.set_ylabel(label)
        ax.grid(True, alpha=0.3)
        if series:
            ax.legend(fontsize=7, ncol=2)
    fig.tight_layout()
    path = out_root / filename
    fig.savefig(path, dpi=140)
    plt.close(fig)
    return path.name


def write_analysis_artifacts(rows: list[dict], out_root: Path) -> list[str]:
    """Write the required auditable tables and consolidated result plots."""
    artifacts: list[str] = []
    failures = [{
        key: row.get(key) for key in (
            "phase", "sweep", "cell_name", "cell_status", "rmw",
            "profile_label", "n_clients", "seed", "failure_reason")
    } for row in rows if not row.get("complete")]
    artifacts.extend(_write_rows(out_root, "failure_accounting", failures))
    slo_rows, variance_rows = _replicate_tables(rows)
    artifacts.extend(_write_rows(out_root, "slo_capacity", slo_rows))
    artifacts.extend(_write_rows(
        out_root, "replicate_variance", variance_rows))
    artifacts.extend(_write_rows(
        out_root, "sustainable_frontiers",
        _sustainable_frontiers(slo_rows)))

    capacity = lambda row: (
        str(row.get("sweep", "")).startswith("single_n")
        and "inverted" not in str(row.get("sweep", "")))
    ha = lambda row: row.get("server_mode") in {
        "active_active", "active_passive", "sharded"}
    rate = lambda row: row.get("sweep") == "rate_n64"
    artifacts.extend([
        _plot_metric(rows, out_root, "plot_delivery.png", [
            ("telemetry_delivery_ratio", "Telemetry delivery ratio"),
            ("command_delivery_ratio", "Command delivery ratio")],
            selection=capacity),
        _plot_metric(rows, out_root, "plot_throughput.png", [
            ("telemetry_received_per_s", "Telemetry delivered/s"),
            ("rpc_success_per_s", "Successful RPC/s")],
            selection=capacity),
        _plot_metric(
            rows, out_root, "plot_rate_frontier.png", [
                ("telemetry_delivery_ratio", "Telemetry delivery ratio"),
                ("rpc_success_ratio", "RPC success ratio"),
                ("rpc_rtt_p99_ms", "RPC RTT p99 (ms)")],
            selection=rate,
            x_key="ros2.centralized.telemetry_period_ms"),
        _plot_metric(rows, out_root, "plot_rpc.png", [
            ("rpc_success_ratio", "RPC success ratio"),
            ("rpc_rtt_p99_ms", "RPC RTT p99 (ms)")],
            selection=capacity),
        _plot_metric(rows, out_root, "plot_readiness.png", [
            ("ready_time_s", "Ready time (s)")], selection=capacity),
        _plot_metric(rows, out_root, "plot_lan_rtt.png", [
            ("link_rtt_mini_ms", "Wi-Fi link RTT (ms)")],
            selection=lambda row: row.get("phase") == "lan"),
        _plot_metric(rows, out_root, "plot_commands.png", [
            ("command_gap_p99_ms", "Command gap p99 (ms)"),
            ("command_duplicate_ratio", "Command duplicate ratio")],
            selection=capacity),
        _plot_metric(rows, out_root, "plot_failover.png", [
            ("command_failover_gap_s", "Command failover gap (s)"),
            ("rpc_failover_gap_s", "RPC failover gap (s)")], selection=ha),
        _plot_metric(rows, out_root, "plot_resources.png", [
            ("server_cpu_peak_pct", "Server CPU peak (%)"),
            ("server_rss_peak_mb", "Server RSS peak (MB)"),
            ("infrastructure_cpu_peak_pct", "Infrastructure CPU peak (%)"),
            ("infrastructure_rss_peak_mb", "Infrastructure RSS peak (MB)")],
            selection=capacity),
        _plot_metric(slo_rows, out_root, "plot_slo_capacity.png", [
            ("relaxed_pass_fraction", "Relaxed SLO pass fraction"),
            ("tight_pass_fraction", "Tight SLO pass fraction")],
            selection=capacity),
    ])
    return artifacts


def evaluate(command: str, scenario_root: Path, out_root: Path) -> None:
    provenance_exists = (out_root / "provenance.json").exists()
    preflight(REPO_ROOT, resumed=provenance_exists)
    # Resumes must retain the original run-start snapshot. Report-time
    # counters and package metadata are appended by finalize_provenance().
    if not provenance_exists:
        write_provenance(out_root)
    generate(scenario_root, (
        json.loads((out_root / "locked_profiles.json").read_text())
        if (out_root / "locked_profiles.json").exists() else None))
    phases = (
        ["tune", "bridge-core", "bridge-ha", "lan"]
        if command == "all" else [command])
    for phase in phases:
        asyncio.run(run_phase(phase, scenario_root, out_root))
        if phase == "tune":
            lock_profiles(out_root, scenario_root)
        combined_report(out_root, scenario_root)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "command",
        choices=["generate", "tune", "bridge-core", "bridge-ha", "lan",
                 "report", "all"],
        nargs="?",
                        default="generate")
    parser.add_argument("--out", default="scenarios/centralized")
    parser.add_argument("--results", default="results/centralized")
    args = parser.parse_args()
    scenario_root = Path(args.out)
    results_root = Path(args.results)
    if not scenario_root.is_absolute():
        scenario_root = REPO_ROOT / scenario_root
    if not results_root.is_absolute():
        results_root = REPO_ROOT / results_root
    if args.command == "generate":
        for path in generate(scenario_root):
            print(path)
    elif args.command == "report":
        summary = combined_report(results_root, scenario_root)
        print(json.dumps({k: v for k, v in summary.items() if k != "rows"},
                         indent=2))
    else:
        evaluate(args.command, scenario_root, results_root)


if __name__ == "__main__":
    main()
